console.log("Rodando o sistema de gerenciamento de jogos")
console.log("aplicação está se conectando ao banco de dados")
console.log("eviando para o GitHub")
console.log("TESTE NO GITHUB")
console.log("teste")
